Subscribe
RossHaluz/project-foodsta pull request #14
Opened 2022-08-28 16:20 UTC by TarasKachmar2022

2022-08-28 20:51 UTC, RossHaluz requested changes
тут незначні правки ще зробити

2022-08-28 20:51 UTC, RossHaluz commented on src/sass/components/_subscribe.scss
> +.form__input{
input перевикористовуєш із компонентів

2022-08-28 20:51 UTC, RossHaluz commented on src/partials/subscribe.html
> +  <div class="container container--sub">
ммодифікатор не вико=ристовується без батьківського елеменента, + --sub це не є модифікатор, модифікатор повинен відповідати на питання "який?". на скількия бачу це просто обгортка секції, то назви їй краще subscribe__wrap

2022-08-28 20:51 UTC, RossHaluz commented on src/partials/subscribe.html
> +    <div class="sub-wrapper">
це так само, модифікатор не може бути без батьківського елемента, + це не є модифікатор

2022-08-28 20:51 UTC, RossHaluz commented on src/sass/components/_subscribe.scss
> +.subscribe__title {
цього не птрібно, ти ж перевикористовуєш із комплнентів

2022-08-28 20:51 UTC, RossHaluz commented on src/sass/components/_subscribe.scss
> +.subscribe .btn--sub{
ця кнопка є у компонентах, їй можна перевикористати, а в стилях просто зпозиціонувати їй

2022-08-29 13:34 UTC, TarasKachmar2022 commented on src/partials/subscribe.html
> +    <div class="sub-wrapper">
це не модифікатор, а мікс

2022-08-29 13:38 UTC, TarasKachmar2022 commented on src/sass/components/_subscribe.scss
> +.subscribe__title {
Там лише добавлений маржин боттом 20px

2022-08-29 13:43 UTC, TarasKachmar2022 commented on src/sass/components/_subscribe.scss
> +.subscribe .btn--sub{
ця кнопка використана зі компонентів але вона відрізняється розміром тому створив btn--sub зараз його перейменовую на btn--changed

2022-08-29 13:50 UTC, TarasKachmar2022 commented on src/partials/subscribe.html
> +  <div class="container container--sub">
переіменував

2022-08-29 13:50 UTC, TarasKachmar2022 commented on src/partials/subscribe.html
> +    <div class="sub-wrapper">
переіменував

2022-08-29 15:51 UTC, RossHaluz approved these changes

2022-08-29 15:51 UTC, merged