html mapkup
RossHaluz/project-foodsta pull request #2
Opened 2022-08-25 15:48 UTC by denius97

2022-08-25 16:13 UTC, RossHaluz commented on src/partials/favorites.html
> +    <h2></h2>
Добав заголовок

2022-08-25 16:13 UTC, RossHaluz commented on src/partials/favorites.html
> +    <p></p>
Добав текст

2022-08-25 16:22 UTC, RossHaluz commented on src/partials/favorites.html
> +    <ul class="card-set">
card-set це допоміжний клас, пороздавай ще такы класи їм

2022-08-25 16:23 UTC, RossHaluz commented on src/partials/favorites.html
> +        <a href="">
тут задай клас і aria-label для оптимізації

2022-08-25 16:26 UTC, RossHaluz commented on src/partials/favorites.html
> +          <picture></picture>
Якщоти вже пишеш picture, то обовязково тоді має бути img. Пропоную поки просо зробити розмытку без picture,  а вже коли будемо оптимызовувати зображення, то просто їх обгорнеш. Верстай сайт так, як ми верстали його з Ярославом, тільки ми вже починаємо з мобілки.

2022-08-25 16:28 UTC, RossHaluz commented on src/partials/favorites.html
> +<section class="section">
щоб не робити купа дівів, ти контейнер можеш пложити в секцію + дай секції ще назву.

2022-08-25 16:28 UTC, RossHaluz commented on src/partials/favorites.html
> +<section class="section">
ложити контейнер в секцію не обовязково, просто як порада

2022-08-25 16:31 UTC, RossHaluz requested changes
Поправити

2022-08-26 08:09 UTC, denius97 commented
закинув нову версію

2022-08-26 08:19 UTC, closed without merging