Footer
RossHaluz/project-foodsta pull request #8
Opened 2022-08-26 17:05 UTC by DenisTunyk

2022-08-27 10:08 UTC, RossHaluz commented on src/partials/footer.html
> +<div class="footer container">
тут повинен бути не div а footer

2022-08-27 10:24 UTC, RossHaluz commented on src/partials/footer.html
> +        <nav class="menu-nav" aria-label="Main">
тег nav використовуєся тільки в хедері як навігація по сайту, використовувати його у футері не варто.

2022-08-27 10:25 UTC, RossHaluz commented on src/partials/footer.html
> +  <nav class="footer__bottom footer-menu" aria-label="Footer Menu Additional">
тут так само, це має бути просто список силок, обгортати їх в нав не потрібно

2022-08-27 10:28 UTC, RossHaluz commented on src/partials/footer.html
> +      <div class="footer__logo">
логотип не потрібно обгортати в дів, ти обгортаєш в дів логотип і посилання і задаєш їм диспле флекс, бо на макеті вони і намоб і на таблет і на деск стоять один навпроти одого. А силі до лого ти перевикоистовуєш просто із хедера, прописувати їх ще раз для футера не потрібно, бо це дубль стилів, що не дуже добре.

2022-08-27 10:34 UTC, RossHaluz requested changes
Потрібно пофіксити

2022-08-27 21:55 UTC, DenisTunyk commented on src/partials/footer.html
> +        <nav class="menu-nav" aria-label="Main">
Змінив

2022-08-27 21:56 UTC, DenisTunyk commented on src/partials/footer.html
> +      <div class="footer__logo">
Тут в мене не виходить. Залишив так як є. Якщо убираю div , то не виходить мобільна версія.

2022-08-27 21:56 UTC, DenisTunyk commented on src/partials/footer.html
> +<div class="footer container">
змінив

2022-08-29 06:07 UTC, RossHaluz approved these changes

2022-08-29 06:07 UTC, merged